data-path = "/opt/besu/data/custom/data" # Path

# Network
p2p-enabled = false

rpc-http-enabled = true
rpc-http-host = "0.0.0.0"
rpc-http-port = 8545
rpc-http-api = ["ADMIN", "ETH", "MINER", "NET", "WEB3"]
rpc-http-cors-origins = ["*"]

host-whitelist = ["all"]

pruning-enabled = true

# Chain
genesis-file = "/etc/besu/genesis.json" # Path to the custom genesis file

# Mining
miner-enabled = true
miner-coinbase = "0xfe3b557e8fb62b89f4916b721be55ceb828dbd73"
