# network
network: "minimal"

# p2p
p2p-enabled: true
p2p-port: 9000

# validators
validator-keys: "/etc/keys/validator_keys:/etc/keys/passwords"
validators-graffiti: "Teku validator"

# Eth 1
eth1-endpoint: "http://besu:8545"

# metrics
metrics-enabled: true
metrics-port: 8008
metrics-interface: "0.0.0.0"
metrics-host-allowlist: [ "*" ]
metrics-categories: [ "BEACON","LIBP2P","NETWORK" ]

# database
data-path: "/opt/teku/data"

# rest api
rest-api-port: 5051
rest-api-docs-enabled: False
rest-api-enabled: True
rest-api-interface: "0.0.0.0"
rest-api-host-allowlist: [ "*" ]

# logging
log-include-validator-duties-enabled: true

eth1-deposit-contract-address: "0xdddddddddddddddddddddddddddddddddddddddd"
