network = "goerli"
data-path = "/opt/besu/data/goerli/data" # Path

# Network
p2p-enabled = true

rpc-http-enabled = true
rpc-http-host = "0.0.0.0"
rpc-http-port = 8545
rpc-http-api = ["ADMIN", "ETH", "MINER", "NET", "WEB3"]
rpc-http-cors-origins = ["*"]

host-whitelist = ["all"]

pruning-enabled = true

# Mining
miner-enabled = false
